name: build

on:
  push:
    branches: [master]
    paths:
      - '.github/workflows/**'
      - 'app/**'
      - 'src/**'
      - 'test/**'
      - 'package.yaml'
      - 'stack*.yaml'
  pull_request:
    branches: [master]
  
jobs:
    build:
      strategy: 
        matrix:
          resolver: 
            - stack
  
      runs-on: ubuntu-latest
  
      steps:
      - uses: actions/checkout@v1  
          
      - name: Install the Haskell Stack 
        run: |
          mkdir -p ~/.local/bin
          curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

      - name: Cache .stack
        id: cache-stack
        uses: actions/cache@v2
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ matrix.resolver }}-${{ hashFiles(format('{0}.yaml', matrix.resolver)) }}
          restore-keys: |
              ${{ runner.os }}-stack
              ${{ runner.os }}

      - name: Install GHC 
        run: |
          stack --stack-yaml=${{ matrix.resolver }}.yaml --no-terminal --install-ghc setup

      - name: Install dependencies
        run: |
          stack --stack-yaml=${{ matrix.resolver }}.yaml --no-terminal build --only-dependencies --fast --test
          
      - name: Build
        id: build
        run: |
          stack --stack-yaml=${{ matrix.resolver }}.yaml --no-terminal build --fast --test --no-run-tests

      ### uncomment the following lines in order to run the tests every time you
      ### push to your repository

      # - name: Test 
      #   id: test
      #   run: |
      #     stack --stack-yaml=${{ matrix.resolver }}.yaml --no-terminal build --fast --test
